const mapCodes: Record<number, string> = {
    0: "D-Water Borderland 1-60 pvp map",
    1: "Erina (Keolloseu)",
    2: "Reikeuseu (Gliter)",
    3: "D-Water Dungeon-1 (D1)",
    4: "D-Water Dungeon-1 Lich's Room (D1-2)",
    5: "Cornwell's Ruin",
    6: "Cornwell's Ruin (Asmodeus's Room)",
    7: "Argilla Ruin",
    8: "Argilla Ruin (Knight's Room)",
    9: "D-Water Dungeon 2 level 1",
    10: "D-Water Dungeon 2 level 2",
    11: "D-Water Dungeon 2 level 3 - Kimuraku level",
    12: "Cloron's Lair level 1",
    13: "Cloron's Lair level 2",
    14: "Cloron's Lair level 3 - Cloron Dragon level",
    15: "Fantasma's Lair level 1",
    16: "Fantasma's Lair level 2",
    17: "Fantasma's Lair level 3 - Fantasma Dragon level",
    18: "Proelium frontier - 1-15 pvp map",
    19: "Willieoseu (Arktuis Village) - 2nd AoL map",
    20: "Keuraijen (Starfumos) - 2nd UoF map",
    21: "Maytreyan - AoL dungeon",
    22: "Maytreyan boss room",
    23: "Aidion Nekria level 1 - UoF map",
    24: "Aidion Nekria level 2 - Astaroth's level",
    25: "Elemental Cave - AoL dungeon",
    26: "Ruber Chaos - UoF dungeon",
    27: "Ruber Chaos level 2 - Queen Mago level",
    28: "Adellia (Huigronn Stronghold) - 3rd AoL map",
    29: "Adeurian (Arena Stronghold) - 3rd UoF map",
    30: "Cantabilian Borderland - pvp 20-30",
    31: "Paros Temple - AoL pvp 20-30 dungeon",
    32: "Rapioru Maze - UoF pvp 20-30 dungeon",
    33: "Fedion Temple - AoL dungeon (map 2)",
    34: "Khalamus House - UoF dungeon (map 2)",
    35: "Apulune - AoL capital",
    36: "Iris - UoF capital",
    37: "Cave of Stigma - AoL dungeon (map 3)",
    38: "Aurizen Ruin - UoF dungeon (map 3)",
    39: "Secret Battle Arena",
    40: "Underground Stadium",
    41: "Prison",
    42: "Auction House",
    43: "Skulleron (Pandorashys) - 4th AoL map",
    44: "Astenes (Lanhaar) - 4th UoF map",
    45: "Deep Desert 1 – pvp map",
    46: "Deep Desert 2 – pvp map",
    47: "Stable Erde (Jungle) – pvp map",
    48: "Cryptic Throne",
    49: "Cryptic Throne",
    50: "Guild Ranking Battle map (GRB)",
    51: "AoL Guild House",
    52: "UoF Guild House",
    53: "AoL Guild Management Office",
    54: "UoF Guild Management Office",
    55: "Sky City level 1",
    56: "Sky City level 2",
    57: "Sky City level 3",
    58: "Sky City - Seraphim level",
    59: "Fedion Temple 2 - AoL dungeon (map 2)",
    60: "Elemental Cave 2 - corrupted!!",
    61: "Cave of Stigma 2 - AoL dungeon (map 3)",
    62: "Khalamus House 2 - UoF dungeon (map 2)",
    63: "Aurizen Ruin 2 - UoF dungeon (map 3)",
    64: "Oblivion Insula - pvp map",
  };
  
  export default mapCodes;